name: Build and Sign Electron App (macOS)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    env:
      CSC_LINK: ${{ secrets.CSC_LINK }}
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm ci

      - name: Build and sign Electron app
        run: npm run build

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: Electron-macOS-build
          path: |
            dist/*.dmg
            dist/*.zip
            dist/*.pkg
